### ISSUE TITLE
user can search for a movie

### ISSUE THREAD

**Issue by qnpham** [qnpham/ajax-project#1]
## 💰 Motivation

User can search for movie.

## 📐 Plan

Display all movies that includes the user's keyword.

## 🖼️ Wireframes

<img width="929" alt="Screen Shot 2022-09-26 at 4 45 04 PM" src="https://user-images.githubusercontent.com/84756451/192399865-2169a68d-3c1b-4ca8-b7e6-a1231483fa06.png">

<img width="929" alt="Screen Shot 2022-09-26 at 4 43 08 PM" src="https://user-images.githubusercontent.com/84756451/192399713-a4cb7405-e471-460f-81f6-3dd93ecc3cc9.png">

## ✅ Task List

- [x] create the home page
- [x] add event listener to search button to listen for a click and submit form
- [x] ensure that the user can only submit if there is a value
- [x] create a view to look at movie search result
- [x] make search result view gets displayed after the user submits a value
- [x] create dummy data
- [x] retrieve all movies with keyword from api and store it in data model.
- [x] create a function to loop and create dom tree of all movies images with search keyword
- [x] remove dummy data
- [x] append dom tree to html document
- [x] ensure search in nav bar is also functional
- [x] clean up everything
