### ISSUE TITLE
User can view a movie page

### ISSUE THREAD

**Issue by qnpham** [qnpham/ajax-project#2]
## 💰 Motivation

Once a user searches for a movie, they'll want to view it.

## 📐 Plan

Display the movie that the user clicks.

## 🖼️ Wireframes

![Screen Shot 2022-09-28 at 10 05 10 AM](https://user-images.githubusercontent.com/84756451/192845176-c3065f8b-1933-4fcd-af46-75cdd9bd7ee3.png)
<img width="848" alt="Screen Shot 2022-09-28 at 12 18 41 PM" src="https://user-images.githubusercontent.com/84756451/192869885-2345c36a-bff0-4766-aee4-b1348590ba1a.png">

## ✅ Task List

- [x] make a view to see a chosen movie and add dummy data
- [x] add an even listener to a parent element of all images and target images
- [x] make it so that if the user clicks on a movie image, find which movie it is in data model
- [x] after finding movie in data model, set the viewing property of data model to the movie
- [x] get data from api with movie id
- [x] set movie page view's content to the movie currently being viewed in the data model.
- [x] on user click, show the movie view
- [x] ensure that if the user clicks "X" hides movie view.
- [x] clean up everything.
