### ISSUE TITLE
User can add movie to a list

### ISSUE THREAD

**Issue by qnpham** [qnpham/ajax-project#3]
## 💰 Motivation

Once the user finds a movie, they would want to save it in a list.

## 📐 Plan

Allow the user to add a movie to list in data model in reverse chronological order.

## 🖼️ Wireframes

<img width="848" alt="Screen Shot 2022-09-29 at 9 03 29 AM" src="https://user-images.githubusercontent.com/84756451/193082321-28b6b5ee-b7fe-48d2-bc9d-cc8e5c0ecf66.png">
<img width="848" alt="Screen Shot 2022-09-29 at 9 01 33 AM" src="https://user-images.githubusercontent.com/84756451/193082350-60ad7d1f-bcc2-46b7-bd0c-526a48e1a0ee.png">

## ✅ Task List

- [x] add a button to add to list and checkmark on movie page
- [x] add a list property in data model
- [x] add an event listener to "+" button
- [x] on button click, the movie that is currently being viewed gets sent to the beginning of list in data model
- [x] on button click, change the "+" button to a checkmark icon to show the user it has been added for that movie
- [x] cleanup everything
