### ISSUE TITLE
User can view list

### ISSUE THREAD

**Issue by qnpham** [qnpham/ajax-project#4]
## 💰 Motivation

Once the user has a list of their chosen movies, they will want to view their list.

## 📐 Plan

Display the user's movie list.

## 🖼️ Wireframes
<img width="800" alt="Screen Shot 2022-09-29 at 10 47 40 PM" src="https://user-images.githubusercontent.com/84756451/193199182-c0c2bf12-e9d8-4421-b6ec-2bf1608042eb.png">
<img width="902" alt="Screen Shot 2022-09-29 at 10 47 53 PM" src="https://user-images.githubusercontent.com/84756451/193199191-240b8aa1-ef0e-4b20-82c9-26be8ea44933.png">

## ✅ Task List

- [x] add a button on home page to view list
- [x] add a button in navbar to view list
- [x] add an event listener to listen for click on both buttons
- [x] make a property in data model to know which view is currently being displayed
- [x] make a view for list
- [x] once "list" is clicked, create dom tree of list in data model and append it to the document
- [x] ensure that search bar is hidden while viewing list
- [x] ensure that closing list is functional
- [x] if user clicks on a movie while viewing list, hide icons
- [x] cleanup everything
