### ISSUE TITLE
User can delete a movie from list

### ISSUE THREAD

**Issue by qnpham** [qnpham/ajax-project#5]
## 💰 Motivation

Allow the user to delete a movie off of their list.

## 📐 Plan

Remove a movie from the user's list.

## 🖼️ Wireframes

<img width="837" alt="Screen Shot 2022-09-30 at 9 22 08 AM" src="https://user-images.githubusercontent.com/84756451/193314548-5e07e6bd-c353-4d46-830a-8819833b84bf.png">
<img width="837" alt="Screen Shot 2022-09-30 at 9 22 23 AM" src="https://user-images.githubusercontent.com/84756451/193314563-6138c896-2c77-43e6-8518-c307e66b24d3.png">

## ✅ Task List

- [x] create a delete button
- [x] create a modal asking if the user is sure they want to delete
- [x] make sure the delete button only shows while user is viewing movie in list
- [x] add an event listener to "-" button to show modal
- [x] If the user clicks no in modal, close the modal.
- [x] if the user clicks yes in modal, remove the current movie from data model and display the list view.
- [x] cleanup
